internalName: mhr_keyboard

locales:
  en:
    name: &bundleName "Eastern Mari Keyboards"
    description: "Mobile OS keyboards for the Eastern Mari language from the Divvun group at UiT."
  nb:
    name: "Eastern Mari tastatur"
    description: "Mobiltastatur for Eastern Mari fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [mhr]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.mhr
    icon: images/mhr-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: mhr_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.mhr
    bundleName: *bundleName
    icon: images/mhr-icon.png
  osx: *AppleID
