locales:
  en:
    name: Eastern Mari Keyboards
    description: >-
      Mobile OS keyboards for the Eastern Mari language from the Divvun group at
      UiT.
  nb:
    name: Eastern Mari tastatur
    description: Mobiltastatur for Eastern Mari fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
