template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 17
template_sha = "346f129f994bbadaaf70e03a281aef7056527a21"

[replacements]
__UND2C__ = "mhr"
__UNDEFINED__ = "Eastern Mari"
__UND__ = "mhr"
